return {}

-- return {
--   "binhtran432k/dracula.nvim",
--   lazy = false,
--   priority = 1000,
--   opts = {
--     style = "default", -- "default", "soft" (darker), or "day" (light)
--     transparent = false,
--     terminal_colors = true,
--     styles = {
--       comments = { italic = true },
--       keywords = { italic = true },
--       sidebars = "dark",
--       floats = "dark",
--     },
--   },
--   config = function()
--     require("dracula").setup()
--     vim.cmd.colorscheme("dracula")
--   end,
-- }
