return {}

-- return {
--   "navarasu/onedark.nvim",
--   priority = 1000,
--   config = function()
--     require("onedark").setup({
--       style = "dark",
--       code_style = {
--         keywords = "italic",
--         strings = "none",
--         functions = "none",
--         variables = "none",
--       },
--       colors = {
--         -- You can define or override named palette colors here if needed
--       },
--       highlights = {
--         -- Keywords
--         ["@keyword"] = { fg = "#F546FF", fmt = "italic" },
--         -- Strings
--         ["@string"] = { fg = "#6DCD5F" },
--         -- Operators
--         ["@operator"] = { fg = "#FF4D97" },
--         -- Constants
--         ["@constant"] = { fg = "#FF9741" },
--         -- Global variables (Identifiers)
--         ["@variable"] = { fg = "#FF415B" },
--         -- Parameters
--         ["@parameter"] = { fg = "#E7A960" },
--         -- Methods/Functions
--         ["@function"] = { fg = "#40A8FF" },
--         ["@method"] = { fg = "#40A8FF" },
--         -- Instance field
--         ["@field"] = { fg = "#FF415B" },
--         -- Static field (often mapped to constant)
--         ["@constant"] = { fg = "#FF9741" },
--       },
--     })
--     require("onedark").load()
--   end,
-- }
